[tool.poetry]
name = "resdx"
version = "0.1.0"
description = ""
authors = ["Big Ladder Software"]

[tool.poetry.dependencies]
python = "^3.7"
Pint = "^0.17"
PsychroLib = "^2.5.0"
matplotlib = "^3.3.4"
scipy = "^1.5.4"
seaborn = "^0.11.1"
pandas = "1.1.5"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
pylint = "^2.7.2"
doit = "*"
tomli = "2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
