[tool.poetry]
name = "resdx"
version = "0.1.0"
description = ""
authors = ["Big Ladder Software"]

[tool.poetry.dependencies]
python = "^3.8"
koozie = "^1.2.2"
PsychroLib = "^2.5.0"
matplotlib = "^3.3.4"
scipy = "^1.6.3"
seaborn = "^0.11.1"
numpy = "1.24.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.3"
doit = "*"
tomli = "2.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
