[tool.poetry]
name = "resdx"
version = "0.1.0"
description = ""
authors = ["Big Ladder Software"]

[tool.poetry.dependencies]
python = ">=3.6,<3.10"
Pint = "^0.17"
PsychroLib = "^2.5.0"
numpy = "1.18.0"
matplotlib = "^3.3.4"
scipy = "^1.5.4"
seaborn = "^0.11.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "^2.7.2"
doit = "^0.33.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
