name: Setup and Test

on: push

jobs:
  build:
    name: Setup
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1
      - name: Install project
        run: poetry install
      - name: Test
        run: poetry run doit
      - name: Upload output
        uses: actions/upload-artifact@v2
        with:
          name: output-${{ matrix.os }}
          path: output