name: Setup and Test

on:
  push:
  schedule:
    - cron: "0 9 * * SUN"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    defaults:
      run:
        shell: bash
    name: ${{ matrix.os }} py${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: bigladder/github-actions/setup-python-poetry@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test
        run: poetry run doit -v2
      - name: Upload output
        uses: actions/upload-artifact@v4
        with:
          name: output-${{ matrix.os }}-py${{ matrix.python-version }}
          path: output
